## Numpy array and basics
- learn about numpy with chai aur code

## Numpy array and basics
- learn about numpy with chai aur code

## Creating array from list

In [ ]:
import numpy as np  # Make sure NumPy is imported

# Creating 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

# Creating 2D array from list of lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [17]:
py_list = [1, 2, 3, 4, 5]  
print("Python list multiplication:", py_list * 2)

np_array = np.array([1, 2, 3, 4, 5]) # element wise multiplication
print("NumPy array multiplication:", np_array * 2)

import time
start_time = time.time()
py_list = [1*2 for i in range(1000000)]
end_time = time.time()
print("Python list multiplication time:", end_time - start_time)


start_time = time.time()
np_array = np.arange(1000000) * 2
end_time = time.time()
print("NumPy array multiplication time:", end_time - start_time)

Python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy array multiplication: [ 2  4  6  8 10]
Python list multiplication time: 0.10563254356384277
NumPy array multiplication time: 0.013555049896240234


### creating array from scratch


In [21]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((3, 4))
print("Ones array: \n", ones)

full =np.full((3, 4), 5)
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(1, 10, 2)
print("Sequence array: \n", sequence)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Random array: 
 [[0.90603905 0.4123312  0.961155  ]
 [0.90479411 0.61580687 0.11298061]]
Sequence array: 
 [1 3 5 7 9]


In [22]:

### Vector, Matrix, Tensor

In [28]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Array properties

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array shape:", arr.shape)
print("Array data type:", arr.dtype)
print("Array size:", arr.size)
print("Array dimension:", arr.ndim)
print("Array item size:", arr.itemsize)

Array shape: (3, 3)
Array data type: int64
Array size: 9
Array dimension: 2
Array item size: 8


## Array Reshaping

In [34]:
arr = np.arange(12)
print("Original array:", arr)

reshaped_arr = arr.reshape((3, 4))
print("Reshaped array: \n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print("Flattened array:", flattened_arr)

# ravel (returns view, instead of copy)
raveled_arr = reshaped_arr.ravel()
print("Raveled array:", raveled_arr)

# transpose
transposed_arr = reshaped_arr.T
print("Transposed array: \n", transposed_arr)

# swapaxes
swapped_arr = reshaped_arr.swapaxes(0, 1)
print("Swapped axes array: \n", swapped_arr)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Swapped axes array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
