## Numpy Array operationa

In [7]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("Negative indexing ", arr[-1])
print("Reverse Slicing",arr[-1::-1])
print("Step Slicing",arr[0:10:2])
print("Step Slicing",arr[0:10:3])


Basic Slicing [3 4 5 6 7]
Negative indexing  10
Reverse Slicing [10  9  8  7  6  5  4  3  2  1]
Step Slicing [1 3 5 7 9]
Step Slicing [ 1  4  7 10]


In [15]:
arr_2d = np.array([[1,2,3]
                ,[4,5,6]
                ,[7,8,9]])
print("specific element",arr_2d[1][1])
print("Entire Row: ",arr_2d[1])
print("Entire Column: ",arr_2d[:,1])

specific element 5
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [20]:
unsorted = np.array([5,2,6,1,3,4])
sorted = np.sort(unsorted)
print("Unsorted Array: ",unsorted)
print("Sorted Array: ",sorted)

arr_2d = np.array([[6,2,3]
                ,[7,8,9],
                [4,5,1],])
print("Unsorted Array: ",arr_2d)
print("Sorted  2D Array by column: ", np.sort(arr_2d, axis=0))
print("Sorted  2D Array by row: ", np.sort(arr_2d, axis=1))

Unsorted Array:  [5 2 6 1 3 4]
Sorted Array:  [1 2 3 4 5 6]
Unsorted Array:  [[6 2 3]
 [7 8 9]
 [4 5 1]]
Sorted  2D Array by column:  [[4 2 1]
 [6 5 3]
 [7 8 9]]
Sorted  2D Array by row:  [[2 3 6]
 [7 8 9]
 [1 4 5]]


## Filter

In [21]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ",even_numbers)    

Even Numbers:  [ 2  4  6  8 10]


In [ ]:
## Filter with mask

In [24]:
mask = numbers > 5
print("Number Greater than 5: ", numbers[mask])

Number Greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing VS np.where()

In [30]:
indices = [0, 2, 4]
print("Numbers at indices: ", numbers[indices])

where_result = np.where(numbers > 5)
print("where_result" , where_result)
print("Numbers Greater than 5: ", numbers[where_result])

Numbers at indices:  [1 3 5]
where_result (array([5, 6, 7, 8, 9]),)
Numbers Greater than 5:  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 2, numbers) # like ternary operator number > 5 ? number * 2 : number
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [35]:
## Adding and removing elements

In [36]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print("Concatenated Array: ",np.concatenate((arr1,arr2)))
print("Stacked Array: ",np.stack((arr1,arr2)))
print("Horizontal Stack: ",np.hstack((arr1,arr2)))
print("Vertical Stack: ",np.vstack((arr1,arr2)))

Concatenated Array:  [ 1  2  3  4  5  6  7  8  9 10]
Stacked Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontal Stack:  [ 1  2  3  4  5  6  7  8  9 10]
Vertical Stack:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Array compatibilty

In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatibilty: ", a.shape == b.shape)
print("compaibility: ",np.stack((a,b,c)).shape)

compatibilty:  True
compaibility:  (3, 3)


In [41]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print("Original Array: \n", original)
print("New Row: ", new_row)
print("With New Row: \n", with_new_row)

with_new_column = np.hstack((original, new_row.reshape(2, 1)))
print("With New Column: \n", with_new_column)

Original Array: 
 [[1 2]
 [3 4]]
New Row:  [5 6]
With New Row: 
 [[1 2]
 [3 4]
 [5 6]]
With New Column: 
 [[1 2 5]
 [3 4 6]]


In [42]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Deleted Array: ",deleted)
inserted = np.insert(arr, 2, 10)
print("Inserted Array: ",inserted)
repeated = np.repeat(arr, 2)
print("Repeated Array: ",repeated)


Deleted Array:  [1 2 4 5]
Inserted Array:  [ 1  2 10  3  4  5]
Repeated Array:  [1 1 2 2 3 3 4 4 5 5]
